# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.BooleanField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('rate', models.IntegerField()),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rates', to='patients.HealthRecord')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=512)),
                ('cell_phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=512)),
                ('user_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RelativeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PersonalInformation')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives_relationships', to='patients.PersonalInformation')),
            ],
        ),
        migrations.AddField(
            model_name='heartrate',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='patients.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='doctorrelationship',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_relationships', to='patients.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='doctorrelationship',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='health_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='patients.HealthRecord'),
        ),
        migrations.AddField(
            model_name='comment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='health_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressure_records', to='patients.HealthRecord'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PersonalInformation'),
        ),
    ]
