# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodpressure',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='heartrate',
            name='patient',
        ),
    ]
